### ISSUE TITLE
Feature Request std::cmp::Ord trait

### ISSUE THREAD

**Issue by rlcomstock3** [abaumhauer/eui48#1]
Could the eui48::MacAddress implement std::cap::Ord?  I am happy to try to help if needed.  I am just learning rust, so I may not be a lot of help.  But am happy to try.

**Comment by abaumhauer** [comment]
I think you meant std::cmp::Order, is that correct? If so, I think that's a great suggestion. If you would like to take a crack at it, I'll work with you and accept your patch. This was my first Rust crate, and would welcome your first Rust patches!On Jan 20, 2017 4:39 PM, rlcomstock3 <notifications@github.com> wrote:Could the eui48::MacAddress implement std::cap::Ord?  I am happy to try to help if needed.  I am just learning rust, so I may not be a lot of help.  But am happy to try.

**Comment by abaumhauer** [comment]
I've merged your changes into version 0.2.
