### ISSUE TITLE
Export to Eui48 array

### ISSUE THREAD

**Issue by porcevader** [abaumhauer/eui48#12]
Some existing modules have been already written to use [u8; 6] as a storage type to store an EUI48 style Mac addresses, and their APIs are defined to be so. 

Importing their data to eui48::MacAddress is feasible via MacAddress::new(), but exporting eui48::MacAddress to [u8; 6] is not directly feasible, but would require separate implementation. 

This issue is to propose to implement pub fn MacAddress::to_array(&self) -> Eui48 {}, which works as an inverse function of ::new().

**Comment by porcevader** [comment]
Commit is ready for review.

**Comment by abaumhauer** [comment]
Accepted commit, bumped to version 0.4.6
