### ISSUE TITLE
Compile time feature to use MacAddressFormat::HexString

### ISSUE THREAD

**Issue by porcevader** [abaumhauer/eui48#13]
A canonical display format of MacAddress, which uses '-' separator, is losing its popular adoption in industry uses. Instead HexString format, which uses ':' separator is more widely used.

This issue is to propose to add a conditional compiler feature, "disp_hexstring". This feature enforces the Display format to use HexString, as used in Debug, and eliminates a burden to explicitly specify the format type in every display case.

**Comment by porcevader** [comment]
A commit is ready for review.

**Comment by abaumhauer** [comment]
Accepted commit, bumped to 0.4.6
