### ISSUE TITLE
Maintenance status ?

### ISSUE THREAD

**Issue by kamek-pf** [abaumhauer/eui48#18]
Hey there,
First, thanks for this library, we use it at work in a bunch of places!

I noticed several PRs are pending and the crate hasn't been updated in a while. 

Would you be interested in introducing additional maintainers ? I'd be glad to help!

**Comment by abaumhauer** [comment]
I just updated all outstanding PRs and pushed version 0.5.0. I'd be interested in adding you as a maintainer.
