### ISSUE TITLE
eui48 into the standard library for rust?

### ISSUE THREAD

**Issue by stephanbuys** [abaumhauer/eui48#4]
Hi @abaumhauer,

Have you considered creating an RFC (I could assist) to get this work merged into the rust standard library? I find it surprising that std::net only caters for IP addresses, even though anyone doing anything remotely serious with networking would probably also be interested in Mac addresses?

For example, `diesel` recently added support for Postgres' MAC address data type, but they implemented it as a simple  [u8; 6]. Having interoperability between crates by using a standardised type might be quite awesome.

Cheers,

**Comment by abaumhauer** [comment]
I would be interested, can't say that I would know where to begin with the RFC process. I'd like to see much better support for all networking in the standard library. I would appreciate any help you're willing to give. Let me know where we should start.

**Comment by stephanbuys** [comment]
Hi @abaumhauer, https://github.com/rust-lang/rfcs/pull/2082 - lets hope it gets somewhere.

**Comment by abaumhauer** [comment]
I would be willing to write the implementation of EUI64. I've looked at it, and it's just the extended format for creating IPv6 addresses given a prefix /64 and generating the lower /64 from the EUI48.Thanks for putting the RFC up.On Jul 26, 2017 3:52 AM, Stephan Buys <notifications@github.com> wrote:Hi @abaumhauer, rust-lang/rfcs#2082 - lets hope it gets somewhere.

**Comment by stephanbuys** [comment]
I think based on the feedback and this announcement: https://users.rust-lang.org/t/announcing-the-http-crate/12123, it is probably better to try polish this crate to conform to the same Lib-Blitz goals to provide a stable/1.0 version of this data type. I'm happy to then try and lobby other crates/users to see if we can get this crate adopted (and solicit some feedback). Having EUI64 completed would be cool too.
